#define SOFTWARE_VERSION_NA
#ifdef VERSION_900
#define SOFTWARE_VERSION_STR "9.00"
#define SOFTWARE_VERSION_900
#undef SOFTWARE_VERSION_NA
#endif
#ifdef VERSION_1100
#define SOFTWARE_VERSION_STR "11.00"
#define SOFTWARE_VERSION_1100
#undef SOFTWARE_VERSION_NA
#endif
#ifdef VERSION_1202
#define SOFTWARE_VERSION_STR "12.02"
#define SOFTWARE_VERSION_1202
#undef SOFTWARE_VERSION_NA
#endif